# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '09' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 09
pod 'RxSwift', '6.2.0'
pod 'RxCocoa', '6.2.0'
pod 'SnapKit', '~> 5.0.0'
pod 'Then'
pod 'Alamofire', '~> 5.4'
pod 'SideMenu'
pod 'Tabman', '~> 2.9'
pod 'Moya', '~> 15.0'
end

