# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
target '09' do
  # Comment the next line if you don't want to use dynamic frameworks
  

  # Pods for 09
pod 'RxSwift', '6.2.0'
pod 'RxCocoa', '6.2.0'
pod 'SnapKit', '~> 5.0.0'
pod 'SideMenu'
pod 'Then'
pod 'Moya', '~> 15.0'
pod 'Moya/RxSwift', '~> 15.0'
end
